[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/wethr"
  to = "/.netlify/functions/wethr"
  status = 200

[[redirects]]
  from = "/api/claude"
  to = "/.netlify/functions/claude"
  status = 200
